[aws]
region = "us-east-1"
bucket_name = "ifrs15-contracts-sunstice-us"
access_key_id = "AKIAVY7IDKSHTOEPMQMH"
secret_access_key = "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"

[users.finance]
email = "finance@sunstice.com"
password_hash = "$2b$12$e4ukEX6RWocXDzzzO4WtwuO48voK4ldS4AN2fGfYFrDLwmjWSeSdq"
name = "Finance"
role = "Equipe Finance"